Create issue
DeskproApps/github pull request #9
Opened 2022-07-27 08:52 UTC by zpawn

https://app.shortcut.com/deskpro/story/78686/github-create-issue

2022-07-28 16:21 UTC, AshleyDawson requested changes
minor changes requested

2022-07-28 16:21 UTC, AshleyDawson commented on src/pages/CreateIssue.tsx
> +            // ...((Array.isArray(values.labels) && values.labels.length > 0)
remove redundant code

2022-07-28 16:21 UTC, AshleyDawson commented on src/pages/CreateIssue.tsx
> +            // @ts-ignore
please use correct types

2022-07-29 08:20 UTC, zpawn commented on src/pages/CreateIssue.tsx
> +            // ...((Array.isArray(values.labels) && values.labels.length > 0)
this is not redundant code, I'll be use it when I figure out how to save the labels

2022-07-29 08:23 UTC, zpawn commented on src/pages/CreateIssue.tsx
> +            // @ts-ignore
done

2022-07-29 08:28 UTC, AshleyDawson approved these changes

2022-07-29 08:28 UTC, merged